/*
* Created on 2026.05.26
* Copyright (c) Youcef Lemsafer
*/
#include <sstream>
#include <string>
#include <stdio.h>
#ifndef _WIN32
#include <sys/wait.h>
#endif

#include <catch2/catch_test_macros.hpp>
#include "number_sequences/smarandache.hpp"

namespace ctd = cutrialdive;

namespace cutrialdive { namespace tests {

    class process_pipe
    {
        process_pipe(process_pipe const &) = delete;
        process_pipe& operator=(process_pipe const &) = delete;
        process_pipe(process_pipe&&) = delete;
    public:
        process_pipe(std::string const & cmd)
        {
            handle_ = 
    #ifdef _WIN32
            _popen
    #else
            popen
    #endif
                        (cmd.c_str(), "w");    
            if(!handle_) {
                throw std::runtime_error{"Create pipe with command `"
                    + cmd + "' failed"};
            }
        }

        void write(char const * buf)
        {
            fputs(buf, handle_);
        }

        auto close()
        {
#ifdef _WIN32
            auto ret = _pclose(handle_);
            handle_ = nullptr;
            return ret;
#else
            auto ret = pclose(handle_);
            handle_ = nullptr;
            if(WIFEXITED(ret))
            {
                return WEXITSTATUS(ret);
            }
            return -1;
#endif            
        }

        ~process_pipe()
        {
            if(handle_) {
                close();
            }
        }

    private:
        FILE* handle_{};
    };

    class ExprTester {
    public:
        explicit ExprTester(size_t gpStackSize = 128*1024*1024)
            : gp_stack_size_(gpStackSize)
        {
            static auto dummy = [&](){
                have_gp_ = std::system(R"-(echo "1 + 2*3" | gp -q > /dev/null 2>&1)-") == 0;
                return 0;
            }();
        }
        template <typename TestFunc>
        void test(TestFunc&& testFunc)
        {
            if(!have_gp_) {
                SKIP("gp not found in PATH");
            } else {
                testFunc();
            }
        }
        int run_test_script(std::string const & script)
        {
            // @todo use a file and keep it in case of failure
            int retcode = 1;
            test([&](){
                process_pipe gpPipe{"gp -q --stacksize " + to_string(gp_stack_size_)};
                gpPipe.write(script.c_str());
                retcode = gpPipe.close();
            });
            return retcode;
        }
    private:
        static bool have_gp_;
        size_t gp_stack_size_;
    };

    bool ExprTester::have_gp_ = false;

    void test_sm_expr_eval(std::string const & expr, char const* expectedValue)
    {
        ExprTester tester;
        std::string const script =
std::string{R"-(/* Generated by cutrialdive_tests */
/*
* Naive version of Smarandache base b
*/
Sm(base, n) = {
    my(v = 0);
    my(i = 1);
    while(i <= n,
        my(digits = 1 + logint(i, base));
        v = v * base^digits + i;
        i = i + 1;
    );
    return(v);
}
expr = ")-"} + expr + R"-(";
expected = )-" + expectedValue + R"-(;
if(eval(expr) != expected, quit(1));
)-";
        CAPTURE(expr);
        CAPTURE(expectedValue);
        REQUIRE(tester.run_test_script(script) == 0);
    }

    template <uint64_t base>
    void check_sm_expr(std::initializer_list<uint64_t> tc)
    {
        for(auto t : tc) {
            auto const expected = "Sm(" + to_string(base) + ", " + to_string(t) + ")";
            test_sm_expr_eval(ctd::smarandache_expr<base>(t), expected.data());
        }
    }
}}


using ctd::tests::test_sm_expr_eval;
using ctd::tests::check_sm_expr;

TEST_CASE("Smarandache expression test", "[.][base 10][pari]")
{
    test_sm_expr_eval(ctd::smarandache_expr<10>(0), "0");
    test_sm_expr_eval(ctd::smarandache_expr<10>(1), "1");
    test_sm_expr_eval(ctd::smarandache_expr<10>(2), "12");
    test_sm_expr_eval(ctd::smarandache_expr<10>(3), "123");
    test_sm_expr_eval(ctd::smarandache_expr<10>(4), "1234");
    test_sm_expr_eval(ctd::smarandache_expr<10>(5), "12345");
    test_sm_expr_eval(ctd::smarandache_expr<10>(6), "123456");
    test_sm_expr_eval(ctd::smarandache_expr<10>(9), "123456789");
    test_sm_expr_eval(ctd::smarandache_expr<10>(10), "12345678910");
    test_sm_expr_eval(ctd::smarandache_expr<10>(11), "1234567891011");
    test_sm_expr_eval(ctd::smarandache_expr<10>(16), "12345678910111213141516");
    check_sm_expr<10>({29, 77, 100, 999, 1000, 1001, 9999, 10000, 10001 });
}

TEST_CASE("Smarandache expression test", "[.][base 2][pari]")
{
    test_sm_expr_eval(ctd::smarandache_expr<2>(0), "0");
    test_sm_expr_eval(ctd::smarandache_expr<2>(1), "1");
    test_sm_expr_eval(ctd::smarandache_expr<2>(2), "6");
    test_sm_expr_eval(ctd::smarandache_expr<2>(3), "27");
    test_sm_expr_eval(ctd::smarandache_expr<2>(4), "220");
    check_sm_expr<2>({5, 7, 8, 9, 15, 16, 17, 31, 32, 33, 2871, 1647, 8192});
}

TEST_CASE("Smarandache expression test", "[.][base 3][pari]")
{
    test_sm_expr_eval(ctd::smarandache_expr<3>(0), "0");
    test_sm_expr_eval(ctd::smarandache_expr<3>(1), "1");
    test_sm_expr_eval(ctd::smarandache_expr<3>(2), "5");
    test_sm_expr_eval(ctd::smarandache_expr<3>(3), "48");
    test_sm_expr_eval(ctd::smarandache_expr<3>(4), "436");
    check_sm_expr<3>({39, 81, 82, 145, 5024, 6560, 6561, 6562});
}

TEST_CASE("Smarandache expression test", "[.][base 4][pari]")
{
    test_sm_expr_eval(ctd::smarandache_expr<4>(0), "0");
    test_sm_expr_eval(ctd::smarandache_expr<4>(1), "1");
    test_sm_expr_eval(ctd::smarandache_expr<4>(2), "6");
    test_sm_expr_eval(ctd::smarandache_expr<4>(3), "27");
    test_sm_expr_eval(ctd::smarandache_expr<4>(4), "436");
    test_sm_expr_eval(ctd::smarandache_expr<4>(5), "6981");
    check_sm_expr<4>({6, 15, 16, 4095, 4096, 4097, 7528});
}

TEST_CASE("Smarandache expression test", "[.][base 16][pari]")
{
    check_sm_expr<16>({0, 1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 17, 
        19, 31, 32, 43, 255, 256, 257, 4095, 4096,
        4097, 6543, 7021, 65535, 65536, 65537});
}

TEST_CASE("Smarandache expression test", "[.][base 17][pari]")
{
    check_sm_expr<17>({0, 1, 2, 3, 4, 5, 6, 7, 8, 16, 17, 
        18, 31, 288, 289, 290, 992, 1499, 4912, 4913,
        4914, 5740});
}
